
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function generateBirthdayMessage(): Promise<string> {
  const prompt = `Generate a short, personalized, and heartwarming birthday message for my girlfriend, Samhitha. The message should be dynamic and feel like it’s speaking directly to her. Keep the core sentiment of love and celebration, mentioning her growth and wishing her well for the future. Start with 'Hey Samhithaaaa,'. End with 'Happy Birthday, my love! 💜💫'. Keep it to one paragraph.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt
  });

  return response.text;
}

export async function generateGiftImage(prompt: string): Promise<string> {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          text: prompt,
        },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  const firstPart = response.candidates?.[0]?.content?.parts?.[0];
  if (firstPart && firstPart.inlineData) {
    const base64ImageBytes: string = firstPart.inlineData.data;
    return `data:image/png;base64,${base64ImageBytes}`;
  }

  throw new Error("No image was generated by the API.");
}
